---
os: linux
dist: xenial
language: ruby

cache:
  bundler: true
  directories:
    - /home/travis/.rvm/
env:
  global:
    - MAKEFLAGS="-j2"

before_install:
  - sudo apt-get update
  - sudo apt-get install libicu-dev icu-doc file libmagic-dev libmagic1 libfile-libmagic-perl pkg-config ruby-pkg-config ruby -y
  - export LDFLAGS="${LDFLAGS} $(icu-config --ldflags) $(pkg-config --libs zlib) -L/usr/lib"
  - env | uniq | sort | uniq
rvm:
  - 1.9.3
  - 2.1.0
  - 2.2.0
  - 2.3.0
  - ree
notifications:
  disabled: true
