name: cooljeanius/linguist
on:
  push:
    branches:
    - "**/*"
  pull_request:
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v4.0.0
    - uses: ruby/setup-ruby@v1.153.0
      with:
        ruby-version: "${{ matrix.rvm }}"
    - run: sudo apt-get update
    - run: sudo apt-get install libicu-dev icu-doc file libmagic-dev libmagic1 libfile-libmagic-perl pkg-config ruby-pkg-config -y
    - run: ICU_LDFLAGS="$(icu-config --ldflags)"; export ICU_LDFLAGS; ZLIB_LDFLAGS="$(pkg-config --libs zlib)"; export ZLIB_LDFLAGS; export LDFLAGS="${LDFLAGS} ${ICU_LDFLAGS} ${ZLIB_LDFLAGS}"
    - run: env | uniq | sort | uniq
    - run: gem install bundler
    - run: bundle install --jobs=3 --retry=3
    - run: rake
#     # This item has no matching transformer
#     - disabled: true
    strategy:
      matrix:
        rvm:
        - 1.9.3-p551
        - 2.0.0-p648
        - 2.1.9
        - 2.2.10
        - 2.3.0
